# Generated by Django 3.1 on 2020-08-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('preview', models.FileField(blank=True, null=True, upload_to='preview/')),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('preview_creation', 'Preview Creation'), ('recoding', 'Recoding'), ('ready', 'Ready')], default='uploading', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('extension', models.CharField(max_length=16)),
                ('primary', models.BooleanField(default=False)),
                ('video_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.videoresource')),
            ],
        ),
    ]
